import React, { useState } from "react";
import { candidateStatuses, employerStatuses, verificationStatuses, fileUrl } from "../utils";

export default function DetailModal({item,isCandidate,onClose,onCandidateUpdate,onEmployerUpdate,SERVER_URL}){
  const [notes,setNotes]=useState(item.adminNotes||"");
  const [status,setStatus]=useState(item.status);
  const [verification,setVerification]=useState(item.verificationStatus||"PENDING");
  const [saving,setSaving]=useState(false);
  async function save(){setSaving(true);try{if(isCandidate) await onCandidateUpdate(item._id,{status,adminNotes:notes});else await onEmployerUpdate(item._id,{status,verificationStatus:verification,adminNotes:notes});}finally{setSaving(false);}}
  return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="modal"><div className="modal-head"><div><span className="eyebrow">{isCandidate?"CANDIDATE PROFILE":"EMPLOYER VERIFICATION"}</span><h2>{isCandidate?item.fullName:item.companyName}</h2><p>{isCandidate?item.email:item.workEmail}</p></div><button onClick={onClose} className="close">×</button></div><div className="modal-body"><div className="detail-grid">{isCandidate?<><Detail label="Phone" value={item.phone}/><Detail label="Location" value={item.currentLocation}/><Detail label="Experience" value={item.totalExperience}/><Detail label="Current / Previous Role" value={item.currentRole}/><Detail label="Industry" value={item.industry}/><Detail label="Preference" value={item.employmentPreference}/><Detail label="Preferred Location" value={item.preferredLocation}/><Detail label="Availability" value={item.availability}/><Detail label="LinkedIn" value={item.linkedinProfile} link/><Detail label="Additional Information" value={item.additionalInformation} full/></>:<><Detail label="Contact Person" value={item.fullName}/><Detail label="Work Email" value={item.workEmail}/><Detail label="Phone" value={item.phone}/><Detail label="Industry" value={item.industry}/><Detail label="Recruitment Type" value={item.recruitmentType}/><Detail label="Hiring Function" value={item.hiringFunction}/><Detail label="Positions" value={item.numberOfPositions}/><Detail label="Requirement Details" value={item.requirementDetails} full/></>}</div>{isCandidate?<div className="document-box"><div><strong>CV / Resume</strong><small>{item.cv?.originalName}</small></div>{item.cv?.path&&<a href={fileUrl(item.cv.path,SERVER_URL)} target="_blank" rel="noreferrer">Open CV ↗</a>}</div>:<div className="document-box docs"><div><strong>Company Verification Documents</strong><small>{item.companyVerificationDocuments?.length||0} document(s)</small></div><div className="doc-links">{(item.companyVerificationDocuments||[]).map((d,i)=><a key={i} href={fileUrl(d.path,SERVER_URL)} target="_blank" rel="noreferrer">{d.originalName} ↗</a>)}</div></div>}<div className="admin-edit"><div><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{(isCandidate?candidateStatuses:employerStatuses).map(x=><option key={x}>{x}</option>)}</select></label>{!isCandidate&&<label>Verification<select value={verification} onChange={e=>setVerification(e.target.value)}>{verificationStatuses.map(x=><option key={x}>{x}</option>)}</select></label>}</div><label>Admin Notes<textarea rows="4" value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Internal notes for the recruitment team…"/></label><button className="gold-btn" onClick={save} disabled={saving}>{saving?"Saving…":"Save Changes"}</button></div></div></div></div>
}
function Detail({label,value,full,link}){return <div className={full?"detail full":"detail"}><small>{label}</small>{link&&value?<a href={value} target="_blank" rel="noreferrer">{value}</a>:<strong>{value||"—"}</strong>}</div>}
