import React from "react";
import { Link } from "react-router-dom";
import SEO from "../components/SEO";
import SectionHeading from "../components/SectionHeading";
import CTA from "../components/CTA";
import { EmployerForm, CandidateForm, ContactForm } from "../components/Forms";
import { COMPANY, INDUSTRIES, FUNCTIONS, PROCESS, SEO as SEO_DATA } from "../data/siteData";
import { Hero, IndustryCard, Solution, FunctionGrid, ProcessSection } from "./pageParts";
import { StatsBand, Marquee, WhyGrid, MissionVision, FAQ, Compare, RolesGrid, NextSteps } from "../components/Extras";
import ScrollLink from "../components/ScrollLink";
import * as D from "../data/siteData";

export function About(){return <><SEO {...SEO_DATA.about} path="/about"/><Hero title="Mumbai-Based. People-Focused. Globally Connected." text="We are a specialised recruitment and talent solutions company connecting exceptional professionals with growing businesses across travel, hospitality, aviation, events, PR and corporate communications." image="https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1800&q=90"><ScrollLink className="btn gold" to="our-story">Our Story →</ScrollLink></Hero><section id="our-story" className="section cream"><div className="container two-col"><div><SectionHeading eyebrow="WHO WE ARE" title="People are more than profiles." text="We believe successful recruitment begins with understanding. Our team takes time to understand your business, culture, requirements and the qualities that matter for the role."/><p>We work with employers looking for capable professionals and candidates looking for meaningful opportunities. Our approach combines focused sourcing, careful screening and clear communication.</p></div><div className="quote-card"><span>“</span><h3>The right connection can create a lasting opportunity.</h3><p>That belief shapes how our team approaches every recruitment requirement.</p></div></div></section><section className="section navy"><div className="container"><SectionHeading light eyebrow="OUR APPROACH" title="We listen before we recruit."/><div className="values-grid">{["Industry Understanding","Human Approach","Quality Talent","Global Perspective"].map((x,i)=><div className="value-card" key={x}><span>0{i+1}</span><h3>{x}</h3><p>{["We understand the industries and roles we support.","We keep communication personal and professional.","We focus on relevant profiles rather than volume.","We bring an India-based perspective with an international outlook."][i]}</p></div>)}</div></div></section><MissionVision items={D.MISSION_VISION}/><StatsBand items={D.STATS}/><WhyGrid tone="cream" eyebrow="WHAT SETS US APART" title="Why businesses and professionals choose NEXORA." items={D.WHY_US.slice(0,3)}/><CTA title="Let's build the right connection." text="Tell us what your business needs or share where you want to go next in your career." primary="Hire Talent" secondary="Submit Your CV"/></>}
